POST http://127.0.0.1:8000/api/pertemuan4/register HTTP/1.1
content-type: application/json
Accept: application/json

{
    "name": "Kekeke",
    "email": "lele@aaad.com",
    "password": "lelelele"
}


###
POST http://127.0.0.1:8000/api/pertemuan4/login HTTP/1.1
content-type: application/json
Accept: application/json

{
    "email": "admin@example.com",
    "password": "12345678"
}


###

POST http://127.0.0.1:8000/api/pertemuan4/login HTTP/1.1
content-type: application/json
Accept: application/json

{
    "email": "pengunjung@example.com",
    "password": "12345678"
}

###

GET http://127.0.0.1:8000/api/pertemuan4/bukus/7 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 8|CjTYWUetMyD85paDMMg3yReLG15KUhpzIDevzBJ7ae0cb816


###

GET http://127.0.0.1:8000/api/pertemuan4/bukus HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer 8|CjTYWUetMyD85paDMMg3yReLG15KUhpzIDevzBJ7ae0cb816