openapi: 3.0.0
info:
  title: Api Documentation
  version: 1.0.0
servers:
  - url: http://127.0.0.1:8000
paths:
  /api/pertemuan5/bukus:
    get:
      summary: Get bukus
      responses:
        200:
          description: A list of bukus
          content:
            application/json:
  /api/pertemuan5/bukus/{buku}:
    get:
      summary: Get buku by id
      responses:
        200:
          description: A single buku
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The ID of the buku
                  title:
                    type: string
                    description: The title of the buku
                  author:
                    type: string
                    description: The author of the buku
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
